sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip
  - pip3 install --user `whoami` crossbar

addons:
  apt:
    packages:
    - python3-pip
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libbz2-dev
    - libsqlite3-dev
    - libncurses5-dev

env:
  global:
    TRAVIS_CARGO_NIGHTLY_FEATURE=""