sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
dist: xenial

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user crossbar autobahn

addons:
  apt:
    packages:
    - python3-pip
    - python3-setuptools
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libbz2-dev
    - libsqlite3-dev
    - libncurses5-dev

env:
  global:
    TRAVIS_CARGO_NIGHTLY_FEATURE=""
    RUST_TEST_THREADS=1